### ISSUE TITLE
Video Submit

### ISSUE THREAD

**Issue by jonathanwichter** [RobiNN1/PHP-Fusion-Infusions#1]
When trying to submit a video by I click on the link that was made when infusing your infusion. It goes back to the main page to the site. http://buhlmodeltrainsociety.a2hosted.com/v9/submit.php?stype=v.

**Comment by RobiNN1** [comment]
Guest can't submit video, that is OK.
If you are signed in, but still redirect you, check if is enabled submitting in videos settings.

**Comment by jonathanwichter** [comment]
It is turned on in the settings.

**Comment by jonathanwichter** [comment]
I would like my members to post videos to the site.

**Comment by RobiNN1** [comment]
Articles, Blogs and other submits, works?

**Comment by jonathanwichter** [comment]
Yes they do

**Comment by RobiNN1** [comment]
If you use v9.0 stable  edit root/submit.php
$modules = array(
    'n' => db_exists(DB_NEWS),
    'p' => db_exists(DB_PHOTO_ALBUMS),
    'a' => db_exists(DB_ARTICLES),
    'd' => db_exists(DB_DOWNLOADS),
    'l' => db_exists(DB_WEBLINKS),
    'b' => db_exists(DB_BLOG),
    'q' => db_exists(DB_FAQS),
    'v' => db_exists(DB_VIDEOS)
);
$submit_types = array(
    'n' => array('link' => INFUSIONS."news/news_submit.php"),
    'p' => array('link' => INFUSIONS."gallery/photo_submit.php"),
    'a' => array('link' => INFUSIONS."articles/article_submit.php"),
    'd' => array('link' => INFUSIONS."downloads/download_submit.php"),
    'l' => array('link' => INFUSIONS."weblinks/weblink_submit.php"),
    'b' => array('link' => INFUSIONS."blog/blog_submit.php"),
    'q' => array('link' => INFUSIONS."faq/faq_submit.php"),
    'v' => array('link' => INFUSIONS."videos/video_submit.php")
);

**Comment by jonathanwichter** [comment]
Is there a way for you to add a center panel showing the most popular videos like NetriX's video infusion for v7?

**Comment by RobiNN1** [comment]
I'm just working on it.

**Comment by RobiNN1** [comment]
Updated https://github.com/RobiNN1/PHP-Fusion-Infusions/commit/0fd0c5c8f0492c13870a93af604bf2f2a4170fa9

**Comment by jonathanwichter** [comment]
Not showing up under panel manger.

**Comment by jonathanwichter** [comment]
<img width="1537" alt="screen shot 2018-01-07 at 8 50 40 am" src="https://user-images.githubusercontent.com/35083828/34650028-e32e6092-f387-11e7-98bd-7385a86cfae0.png">

**Comment by RobiNN1** [comment]
Because panel is installed scoll down in you site

**Comment by jonathanwichter** [comment]
oh ok lol thanks!

**Comment by RobiNN1** [comment]
Is installed automatically with infusion
