### ISSUE TITLE
Content Creator: 2 errors after install on localhost

### ISSUE THREAD

**Issue by helmuthm** [RobiNN1/PHP-Fusion-Infusions#3]
![contentcreator-2](https://user-images.githubusercontent.com/9512774/36327905-624527c4-1360-11e8-96c4-b1c5c0118e9e.png)
![contentcreator-1](https://user-images.githubusercontent.com/9512774/36327906-6289c64a-1360-11e8-8361-1a45775335c5.png)

**Comment by RobiNN1** [comment]
It's not a issue in Content Creator. PHPMailer is core function.
