### ISSUE TITLE
Video center panel

### ISSUE THREAD

**Issue by jonathanwichter** [RobiNN1/PHP-Fusion-Infusions#4]
The preview panel for the video do not change they stay on the same videos when their are new videos added. Also is there a way to change panel to make one for the photo gallery?

Thanks,
John

**Comment by RobiNN1** [comment]
If I understand, do you want a latest gallery panel or something?

**Comment by jonathanwichter** [comment]
yes, and is their away to show the latest videos that have been added?

Thanks,
John

**Comment by RobiNN1** [comment]
https://github.com/RobiNN1/PHP-Fusion-Infusions/blob/master/infusions/videos/additional_files/infusions/latest_videos_panel/latest_videos_panel.php

**Comment by jonathanwichter** [comment]
does that change the way the videos are viewed by the latest? What line have you changed in it?
Do you have an idea on the photo gallery panel to show the same thing?

**Comment by RobiNN1** [comment]
Sorry, I don't have time for this. Maybe later. I have lot of work.

**Comment by jonathanwichter** [comment]
what line did you change in the latest video panel to show an updated video list
