### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jonathanwichter** [RobiNN1/PHP-Fusion-Infusions#6]
The theme does not change on the site, but does give a notification that it did. Does the theme change for all users or just the user that is login? I added screen shots of the other themes that I have installed.

Thanks,
John

**Comment by RobiNN1** [comment]
Did you read this?

https://github.com/RobiNN1/PHP-Fusion-Infusions/blob/master/infusions/theme_switcher_panel/README.md
