### ISSUE TITLE
where do I put the code to make it work?

### ISSUE THREAD

**Issue by jonathanwichter** [RobiNN1/PHP-Fusion-Infusions#7]
Their is no set theme code in my maincore.php

This is what I have:
[maincore.zip](https://github.com/RobiNN1/PHP-Fusion-Infusions/files/1974493/maincore.zip)

**Comment by RobiNN1** [comment]
Line 254

**Comment by jonathanwichter** [comment]
Will this change for the hole site or just the user?

**Comment by RobiNN1** [comment]
Only for user
