### ISSUE TITLE
Different View for videos

### ISSUE THREAD

**Issue by jonathanwichter** [RobiNN1/PHP-Fusion-Infusions#8]
Is their a way to have 3x3 video grid? I tried to edit this file but with no luck. I am trying to make it look like NetriX infusion instead of a list.

**Comment by RobiNN1** [comment]
https://github.com/RobiNN1/PHP-Fusion-Infusions/blob/master/infusions/videos/templates/videos.php#L94 change col-lg-3 to col-lg-4
